# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# GenMF_bot.py
# Created on: 2014-05-23 13:30:25.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

try:
    import arcpy
    from arcpy import env
except:
    print ('\n'
           'ERROR: Unable to import the "ARCPY" module. \n\n'
           'The program will not work without this module. \n'
           'Please ensure that ARC9.3 or newer is installed and \n'
           'the python path includes a path to ARCPY. \n\n')

# Check out any necessary licenses
if arcpy.CheckExtension("spatial") == "Available":
    arcpy.CheckOutExtension("spatial")
else:
    print ('ERROR: Spatial Analyst is required for this tool, but \n'
           'the license is unavailable. Please work with your IT \n'
           'staff to ensure that your installation of ARC includes \n'
           'a license for Spatial Analyst. \n')

env.overwriteOutput = True

input_raster = "D:\\PFJData2\\Projects\\NAQWA\\Cycle3\\FWP\\ARC\\Soller_DTBr\\bedrockTopo.img"
model_node_shapefile = "D:\\PFJData2\\Projects\\NAQWA\\Cycle3\\FWP\\ARC\\FWPvert_nodes1000_UTMft.shp"
Bilinear_interpolation = "true"

# Process: Extract Multi Values to Points
print "extract multivalues to points"
arcpy.gp.ExtractMultiValuesToPoints_sa(model_node_shapefile, input_raster, Bilinear_interpolation)


arcpy.CheckInExtension("spatial")

# Next Steps:  Import into GWvistas as bot property.  Then enforce at least 5ft thickness between top & bot in GWV
# write DIS file and generate SFR package with SFR maker